### ISSUE TITLE
Mark segement for deletion

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-editor#125]
Some ideas for naming: 

- If we want two different titles:
    - Mark the segment at the current position as to be deleted in the final cut.
    - Mark the segment at the current position as to be kept in the final cut.
- If we want just one title
    - Mark or unmark the segment at the current position as to be deleted.

![Screenshot from 2021-01-22 17-13-47](https://user-images.githubusercontent.com/1008395/105516486-3a8ce100-5cd6-11eb-8bba-343cddddc577.png)

**Comment by Arnei** [comment]
Aye, those descriptions look like they'd be clearer to users.

Got any preferences on "two different titles" vs "just one title"? I'd lean towards one title, because it may help in clearing up confusion for some users that are wondering where their delete button has suddenly vanished to (better presents the dual functionality of the button to users).
