### ISSUE TITLE
Skip selection of a single workflow

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-editor#128]
In most cases, it's best to not let users select different  workflows but select one they should use for processing. If there is just one workflow we should completely hide the workflow selection instead of presenting a selection with a single workflow.

Related code:

https://github.com/elan-ev/opencast-editor/blob/35e3f668c4b3d26873b3dde228156fd563e74ada/src/main/WorkflowSelection.tsx#L32-L38

**Comment by Arnei** [comment]
So in the case of a single workflow, we'd show the user a page similar to the current "Save" page? E.g. 
```
Start processing changes

Your changes will be saved and processed with Opencast with the workflow `some workflow name`.
This may take some time. Start processing?

`No` `Yes`
```

Your description for this issue makes me wonder if we should be presenting the workflow selection (and configuration) to the user at all. So instead of showing the workflow selection everytime, we'd show something like the above ("Do you want to start processing with these defaults?"), and only offer up workflow selection after the user clicks on a button that says something like "Let me configure everything!".

**Comment by lkiesow** [comment]
Let's get more input on this. I can see opinions diverging here.

- I would probably show the selection if there are more than one workflow (which means the admin chose to present more than one)
- I would probably show the options if there are any (which means the admin chose to add some

**Comment by Arnei** [comment]
No idea why i reopened this, it should be closed.

Currently, if there is only one workflow, the user will merely be told that processing is started with the Workflow "WorkflowName". The selection is shown if there is more than workflow.
