### ISSUE TITLE
Metadata: Field names not displayed

### ISSUE THREAD

**Issue by oas777** [elan-ev/opencast-editor#233]
The majority of fields don't have names in Firefox and Chrome (Windows):
![metadata](https://user-images.githubusercontent.com/1752342/112027665-adc89d00-8b37-11eb-9006-2a55024fe545.JPG)

**Comment by oas777** [comment]
PS: Same on OS X (Safari, Firefox)

**Comment by Arnei** [comment]
I'm having trouble reproducing the issue. Can you give more information on how you tested this, such as the event and the test deployment you used if you used one at all (e.g. test.editor.opencast.org/214/2021-03-22_15-54-16/) ?

**Comment by oas777** [comment]
I used the URL Lars provided: https://test.editor.opencast.org/214/2021-03-10_14-52-32/.

**Comment by oas777** [comment]
PS: The field names are visible in your URL https://test.editor.opencast.org/214/2021-03-22_15-54-16/. However, the fields themselves are filled already. 
![metadata](https://user-images.githubusercontent.com/1752342/112181377-afa86400-8bfc-11eb-87d0-36955dc77706.png)

**Comment by Arnei** [comment]
Alright, then this issue has been fixed with the more recent updates to the metadata pull request. Closing this.

The `test.editor.opencast.org` URLs are automatically generated after a pull request receives an update. To ensure that you are testing the latest version, take a look at the comments in the PR (in this case #214), and look for the latest comment with such an URL.
